definitions:
  cache_posix: &cache_posix
    cache:
      cache_paths:
        - /Users/builder/cached_files/
    scripts:
      - |
        mkdir -p $HOME/cached_files
        touch "$HOME/cached_files/cached_$(date -u "+%Y-%m-%d_%H:%M:%S")_build_$CM_BUILD_ID"
        ls -la $HOME/cached_files
workflows:
  default-workflow:
    name: Build iOS and Android
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: 14
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build appbundle --debug
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log

  tests-only:
    name: Tests only, with trigger
    max_build_duration: 10
    environment:
      node: 16.15.0
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - flutter packages pub get

  cache-test-m1:
    name: cache test on M1
    max_build_duration: 5
    instance_type: mac_mini_m1
    <<: *cache_posix

  cache-test-linux:
    name: cache test on linux
    max_build_duration: 5
    instance_type: linux
    <<: *cache_posix

  cache-test-windows:
    name: cache test on windows
    max_build_duration: 5
    instance_type: windows_x2
    cache:
      cache_paths:
        - $HOME\cached_relative\
        - C:\Users\builder\cached_absolute\
    scripts:
      - |
        New-Item -ItemType Directory -Force -Path $HOME/cached_relative
        New-Item ("$HOME\cached_relative\" + (Get-Date -UFormat "+%Y-%m-%d_%H-%M-%S") + "_" + ($Env:CM_BUILD_ID))
        New-Item -ItemType Directory -Force -Path $HOME/cached_absolute
        New-Item ("$HOME\cached_absolute\" + (Get-Date -UFormat "+%Y-%m-%d_%H-%M-%S") + "_" + ($Env:CM_BUILD_ID))
        ls $HOME/cached_relative
        ls $HOME/cached_absolute

  cache-bomb:
    name: cache bomb theory test
    max_build_duration: 120
    cache:
      cache_paths:
        - $HOME/itsabomb
    scripts:
      - |
        mkdir $HOME/itsabomb
        sudo dd if=/dev/random of=$HOME/itsabomb/boom bs=1024 count=10485760

  logs-bomb:
    name: logs bomb theory test
    max_build_duration: 120
    scripts:
      - |
        # output 20 MB of random data to stdout
        base64 /dev/urandom | head -c 20000000
        exit 1

  test-debug-macos:
    name: Test debug build on macOS
    max_build_duration: 30
    cache:
      cache_paths:
        - $HOME/.config
        - $FCI_BUILD_DIR/.metadata
    scripts:
      - flutter --version

  test-emulator-linux:
    name: Tests Android emulator under linux
    max_build_duration: 10
    scripts:
      - |
        flutter emulators --launch emulator
        adb wait-for-device
        adb devices
          
  test-flutter-stable-linux:
    name: Test flutter stable on Linux
    max_build_duration: 3
    instance_type: linux
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - flutter --version
      
  sleep-well-macos-m1:
    name: 2h sleep on m1 macOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      unity: 2020.3.15f2
      groups:
        - test
    scripts:
      - sleep 7200

  sleep-well-macos:
    name: 2h sleep on macOS
    max_build_duration: 120
    instance_type: mac_pro
    environment:
      groups:
        - test
    cache:
      cache_paths:
        - $HOME/.config
        - $FCI_BUILD_DIR/.metadata
    scripts:
      - sleep 7200

  sleep-well-linux:
    name: 2h sleep on Linux
    environment:
      groups:
        - test
    max_build_duration: 120
    instance_type: linux
    scripts:
      - ssh-add -L
      - sleep 7200

  sleep-well-windows:
    name: 2h sleep on Windows
    environment:
      groups:
        - test
    max_build_duration: 120
    instance_type: windows_x2
    scripts:
      - ssh-add -L
      - sleep 7200

  test-flutter-stable-macos:
    name: Test flutter stable on macOS
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - flutter --version

  test-flutter-master-macos:
    name: Test flutter master on macOS
    max_build_duration: 3
    instance_type: mac_mini_m1
    environment:
      flutter: master
    scripts:
      - flutter --version

  ndk-test:
    name: Test custom NDK version
    instance_type: mac_pro
    environment:
      xcode: edge
      ndk: r22b
    scripts:
      - echo "Build"
      
  pyenv-test:
    name: Try temp fix for pyenv
    instance_type: linux
    environment:
      vars:
        PYENV_ROOT: "/home/builder/.pyenv"
        PYENV_SHELL: "zsh"
    scripts:
      - name: Try py3.6 venv
        script: |
          export PYENV_ROOT=/home/builder/.pyenv PYENV_SHELL=zsh PATH=/home/builder/.pyenv/bin:$PATH
          pyenv install 3.6.12
          pyenv local 3.6.12
          pyenv exec python -m venv venv
          source venv/bin/activate
          python -V
