workflows:
  build-ios:
    name: Build iOS
    environment:
      xcode: 16.2
    scripts:
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER --no-codesign
    artifacts:
      - /Users/builder/clone/build/ios/iphoneos/Runner.app
  empty:
    name: Empty
    scripts:
      - echo "empty"
  cache-test:
    name: Cache random data
    cache:
      cache_paths:
        - ~/dummy-cache
    inputs:
      size:
        description: Number of bytes to cache
    scripts:
      - sudo dd if=/dev/random of=/Users/builder/dummy-cache bs=1 count=${{ inputs.size }} && sudo chmod 666 /Users/builder/dummy-cache
