definitions:
  scripts:
    - &echo_with_substitution
      name: Echo with substitution using the bash way
      script: |
        echo $(whoami)
        echo $(flutter version)


workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: 12.4
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build apk --debug
      - find . -name "Podfile" -execdir pod install \;
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

  tests-only:
    name: Tests only
    max_build_duration: 10
    instance_type: linux
    scripts:
      - flutter packages pub get
    artifacts:
      - flutter_drive.log

  NFS goes down:
    name: All your NFS are belong to us!
    max_build_duration: 3
    cache:
      cache_paths:
        - $HOME/.config
    instance_type: mac_mini
    environment:
      xcode: 12.4
    scripts:
      - showmount -e 10.22.1.3 || true

  test-debug-macos:
    name: Test debug build on macOS
    max_build_duration: 30
    cache:
      cache_paths:
        - $HOME/.config
        - $FCI_BUILD_DIR/.metadata
    environment:
      xcode: 12.4
    scripts:
      - flutter --version

  test-emulator-linux:
    name: Tests Android emulator under linux
    max_build_duration: 10
    instance_type: linux_x2
    scripts:
      - |
        flutter emulators --launch emulator
        adb wait-for-device
        adb devices
          
  test-flutter-stable-linux:
    name: Test flutter stable on Linux
    max_build_duration: 3
    instance_type: linux
    cache:
      cache_paths:
        - $HOME/.config
        - $FCI_BUILD_DIR/.metadata
    scripts:
      - flutter --version

  sleep-well-macos:
    name: 2h sleep on macOS
    max_build_duration: 120
    environment:
      xcode: 12.4
    cache:
      cache_paths:
        - $HOME/.config
        - $FCI_BUILD_DIR/.metadata
    scripts:
      - sleep 7200
      - flutter --version

  test-flutter-stable-macos:
    name: Test flutter stable on macOS
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      xcode: 12.4
    scripts:
      - flutter --version

  test-flutter-1.22.6-linux:
    name: Test flutter 1.22.6 on Linux
    max_build_duration: 3
    instance_type: linux
    environment:
      flutter: 1.22.6
    scripts:
      - flutter --version

  test-flutter-1.22.6-macos:
    name: Test flutter 1.22.6 on macOS
    max_build_duration: 3
    instance_type: mac_mini
    environment:
      xcode: 12.4
      flutter: 1.22.6
    scripts:
      - flutter --version
