definitions:
  scripts:
    - &echo_with_substitution
      name: Echo with substitution using the bash way
      script: |
        echo $(whoami)
        echo $(flutter version)


workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    instance_type: linux
    environment:
      flutter: stable
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build apk --debug
      - find . -name "Podfile" -execdir pod install \;
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - remarkov@gmail.com
  tests-only:
    name: Tests only
    max_build_duration: 10
    instance_type: linux
    scripts:
      - flutter packages pub get
    artifacts:
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - remarkov@gmail.com          


  test-debug-macos:
    name: Test debug build on macOS
    max_build_duration: 30
    instance_type: zzz_debug_vladimir_mac_mini
    environment:
      xcode: 12.4
    scripts:
      - flutter --version

test-emulator-linux:
    name: Tests Android emulator under linux
    max_build_duration: 10
    instance_type: linux_x2
    scripts:
      - |
        flutter emulators --launch emulator
        adb wait-for-device
        adb devices
          
  test-flutter-stable-linux:
    name: Test flutter stable on Linux
    max_build_duration: 3
    instance_type: linux
    environment:
      xcode: 12.4
    scripts:
      - flutter --version

  test-1min-sleep-macos:
    name: Test 1 min sleep on macOS
    max_build_duration: 3
    instance_type: mac_mini
    environment:
      xcode: 12.4
    scripts:
      - sleep 60
      - flutter --version

  test-flutter-stable-macos:
    name: Test flutter stable on macOS
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      xcode: 12.4
    scripts:
      - flutter --version

  test-flutter-1.22.6-linux:
    name: Test flutter 1.22.6 on Linux
    max_build_duration: 3
    instance_type: linux
    environment:
      xcode: 12.4
      flutter: 1.22.6
    scripts:
      - flutter --version

  test-flutter-1.22.6-macos:
    name: Test flutter stable on macOS
    max_build_duration: 3
    instance_type: mac_mini
    environment:
      xcode: 12.4
      flutter: 1.22.6
    scripts:
      - flutter --version
