workflows:
  build-ios:
    name: Build iOS
    environment:
      xcode: 15.1
    scripts:
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER --no-codesign
    artifacts:
      - /Users/builder/clone/build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - remarkov+c1@gmail.com
          - remarkov+c2@gmail.com
          - remarkov+c2@gmail.com
        notify:
          success: true
  empty:
    name: Empty
    environment:
      xcode: 15.3
    scripts:
      - echo "empty"
