workflows:
  build-ios:
    name: Build iOS
    environment:
      xcode: edge
    scripts:
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER --no-codesign
    artifacts:
      - /Users/builder/clone/build/ios/iphoneos/Runner.app
  empty-20.04:
    name: Empty 20.04
    instance_type: linux_x2
    environment:
      ubuntu: 20.04
    scripts:
      - lsb_release -d
  empty-24.04:
    name: Empty 24.04
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
    scripts:
      - lsb_release -d
  cache-test:
    name: Cache random data
    cache:
      cache_paths:
        - ~/dummy-cache
    inputs:
      size:
        description: Number of MiB to cache
    scripts:
      - sudo dd if=/dev/random of=/Users/builder/dummy-cache bs=1048576 count=${{ inputs.size }} && sudo chmod 666 /Users/builder/dummy-cache
