workflows:
  new-one:
    name: Added workflow
    scripts:
      - echo $?
  default-workflow:
    name: Build iOS and Android
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: 14
    scripts:
      - |
        # set up debug keystore
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
          -alias androiddebugkey \
          -keypass android \
          -keystore ~/.android/debug.keystore \
          -storepass android \
          -dname 'CN=Android Debug,O=Android,C=US' \
          -keyalg 'RSA' \
          -keysize 2048 \
          -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter build appbundle --debug
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - '*.snap'
      - build/windows/**/*.msix
      - flutter_drive.log

  tests-only:
    name: Tests only, with trigger
    max_build_duration: 10
    environment:
      node: 16.15.0
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: true

    scripts:
      - flutter packages pub get

  quick-cache-test:
    name: quick cache test
    max_build_duration: 3
    cache:
      cache_paths:
        - $HOME/cached_files/
    scripts:
      - |
        mkdir -p $HOME/cached_files
        touch "$HOME/cached_files/cached_$(date -u "+%Y-%m-%d_%H:%M:%S")_build_$CM_BUILD_ID"
        ls -la $HOME/cached_files

  true:
    name: boolean
    instance_type: linux
    max_build_duration: 3
    environment:
      flutter: dev
      xcode: 12.4
    scripts:
      - flutter --version

  3.14:
    name: float
    instance_type: linux
    max_build_duration: 3
    environment:
      xcode: 12.4
    scripts:
      - flutter --version

  cache-bomb:
    name: cache bomb theory test
    max_build_duration: 120
    cache:
      cache_paths:
        - $HOME/itsabomb
    instance_type: mac_mini
    environment:
      xcode: 12.4
    scripts:
      - |
        mkdir $HOME/itsabomb
        sudo dd if=/dev/random of=$HOME/itsabomb/boom bs=1024 count=10485760

  test-debug-macos:
    name: Test debug build on macOS
    max_build_duration: 30
    cache:
      cache_paths:
        - $HOME/.config
        - $FCI_BUILD_DIR/.metadata
    environment:
      xcode: 12.4
    scripts:
      - flutter --version

  test-emulator-linux:
    name: Tests Android emulator under linux
    max_build_duration: 10
    scripts:
      - |
        flutter emulators --launch emulator
        adb wait-for-device
        adb devices
          
  test-flutter-stable-linux:
    name: Test flutter stable on Linux
    max_build_duration: 3
    instance_type: linux
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - flutter --version

  sleep-well-macos:
    name: 2h sleep on macOS
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      groups:
        - test
      xcode: 12.5
    cache:
      cache_paths:
        - $HOME/.config
        - $FCI_BUILD_DIR/.metadata
    scripts:
      - sleep 7200

  sleep-well-linux:
    name: 2h sleep on Linux
    environment:
      groups:
        - test
    max_build_duration: 120
    instance_type: linux
    scripts:
      - ssh-add -L
      - sleep 7200

  sleep-well-windows:
    name: 2h sleep on Windows
    environment:
      groups:
        - test
    max_build_duration: 120
    instance_type: windows_x2
    scripts:
      - ssh-add -L
      - sleep 7200

  test-flutter-stable-macos:
    name: Test flutter stable on macOS
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      xcode: latest
    scripts:
      - flutter --version

  test-flutter-1.22.6-linux:
    name: Test flutter 1.22.6 on Linux
    max_build_duration: 3
    instance_type: linux
    environment:
      flutter: 1.22.6
    scripts:
      - flutter --version

  test-flutter-1.22.6-macos:
    name: Test flutter 1.22.6 on macOS
    max_build_duration: 3
    instance_type: mac_mini
    environment:
      xcode: 13.2
      flutter: 1.22.6
    scripts:
      - flutter --version

  test-flutter-master-macos:
    name: Test flutter master on macOS
    max_build_duration: 3
    instance_type: mac_mini
    environment:
      xcode: 13.2
      flutter: master
    scripts:
      - flutter --version

  ndk-test:
    name: Test custom NDK version
    instance_type: mac_pro
    environment:
      xcode: edge
      ndk: r22b
    scripts:
      - echo "Build"
      
  pyenv-test:
    name: Try temp fix for pyenv
    instance_type: linux
    environment:
      vars:
        PYENV_ROOT: "/home/builder/.pyenv"
        PYENV_SHELL: "zsh"
    scripts:
      - name: Try py3.6 venv
        script: |
          export PYENV_ROOT=/home/builder/.pyenv PYENV_SHELL=zsh PATH=/home/builder/.pyenv/bin:$PATH
          pyenv install 3.6.12
          pyenv local 3.6.12
          pyenv exec python -m venv venv
          source venv/bin/activate
          python -V
